title: Lythseed
tagline: Information Technology 
author: Temitayo Olaleye-Otunla 
description: Information Technology 
name: Lythseed
markdown: kramdown
twitter: 
   username: lythseed
   card: summary
facebook:
  publisher: https://facebook.com/lythseed
social:
  name: Lythseed
  links:
    - https://x.com/lythseed
    - https://www.facebook.com/lythseed
    - https://www.linkedin.com/company/lythseed
    - https://github.com/lythseed
   
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
